---
# file: roles/nfs-server/tasks/main.yml
- name: Install requirements
  apt:
    pkg: nfs-common

- name: Create config directory for non-root user
  file:
    path: /mnt/share
    state: directory
    mode: "0777"

- name: Mount NFS on the client side
  mount:
    fstype: nfs
    opts: defaults
    state: mounted
    src: "{{ hostvars[groups.master.0].internal_ip }}:/mnt/share"
    path: "/mnt/share"
  register: result
  until: result is not failed
  retries: 12 # Wait up to 1 min
  delay: 5
