function: minio
payload:
  images:
    - "sample000.png"
  service_ip: "<ip>"
  service_port: <port>
  access_key: "<key>"
  secret_key: "<secret>"
  
# function: mongodb
# payload:
#   connection_string: mongodb://<user>:<password>@<host>/<database> 
#   name: "<username>"

# function: pv
# payload:
#   image: sample.png

localBackend:
  service_ip: "<ip>"
  service_port: <port>
  access_key: "<key>"
  secret_key: "<secret>"
remoteBackend:
  service_ip: "<ip>"
  service_port: <port>
  access_key: "<key>"
  secret_key: "<secret>"

clusters:
  - name: <cluster-name>
    prometheus: <ip>:<port>
    openwhisk: <ip>