function: minio
payload:
  images:
    - "sample000.png"
    - "sample001.png"    

localBackend:
  service_ip: "138.246.235.42"
  service_port: 31003
  access_key: "<key>"
  secret_key: "<secret>"
remoteBackend:
  service_ip: "34.105.65.71"
  service_port: 9000
  access_key: "<key>"
  secret_key: "<secret>"

clusters:
  - name: local
    prometheus: localhost:8080
    openwhisk: 138.246.235.42
