---
# file: roles/k8s-worker/tasks/main.yml
- name: Add a GPG key for the packages
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: True

- name: Add repository for kubernetes
  apt_repository:
    repo: deb  http://apt.kubernetes.io/  kubernetes-xenial  main
    state: present
  become: True

- name: Install a list of packages
  apt:
    pkg:
      - kubeadm=1.18.3-00
      - kubelet=1.18.3-00
      - kubectl=1.18.3-00
  become: True

- name: Prevent packages from being upgraded.
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubeadm
    - kubelet
    - kubectl
  become: True

- name: Add IP address to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ inventory_hostname }}$"
    line: "{{ hostvars[inventory_hostname].ansible_host }} {{ inventory_hostname }}"
    state: present
  become: True

- name: Copy cloud config to host
  template:
    src: "{{ role_path }}/templates/cloud.conf.j2"
    dest: /etc/kubernetes/cloud-config
  become: True

- name: Copy kubeadm-join-config to host
  copy:
    src: "{{ playbook_dir }}/from_remote/{{ cluster_name }}-master-01/kubeadm-join-config.yml"
    dest: $PWD/kubeadm-join-config.yml
  register: result
  until: result is not failed
  retries: 36 # Wait up to 3 min for the file to be created
  delay: 5

- name: Join cluster
  command: kubeadm join -v=6 --config kubeadm-join-config.yml
  become: True
