---
# file: roles/openwhisk/tasks/main.yml
- name: Label node for running openwhisk
  command: kubectl label node {{ ansible_hostname }} openwhisk-role=core
  ignore_errors: True

- name: Copy mycluster to host
  template:
    src: "{{ role_path }}/templates/mycluster.yaml.j2"
    dest: $PWD/mycluster.yaml
    mode: "0644"

- name: Clone Openwhisk's git repository
  git:
    repo: https://github.com/apache/openwhisk-deploy-kube.git
    dest: $PWD/openwhisk
    force: yes

- name: Get Helm releases
  shell: /snap/bin/helm list -A
  register: helm_releases

- name: Install Openwhisk
  command: /snap/bin/helm install owdev openwhisk/helm/openwhisk -n openwhisk --create-namespace -f mycluster.yaml
  when: helm_releases.stdout.find('owdev') == -1

- name: Label node for running openwhisk
  command: kubectl label nodes --all openwhisk-role=invoker --overwrite

- name: Install Openwhisk CLI
  unarchive:
    src: https://github.com/apache/openwhisk-cli/releases/download/latest/OpenWhisk_CLI-latest-linux-amd64.tgz
    dest: /usr/bin
    remote_src: yes
  become: True

- name: Set CLI properties
  command: "wsk property set --apihost {{ ansible_default_ipv4.address }}:{{ node_port }} --auth {{ auth_key }}"

- name: Update root_url and disable anonymous login
  command: kubectl -n openwhisk set env deployment/owdev-grafana GF_SERVER_ROOT_URL=http://localhost:8001/api/v1/namespaces/openwhisk/services/http:owdev-grafana:http/proxy/ GF_AUTH_ANONYMOUS_ENABLED=false

- name: Add bitnami repo
  command: /snap/bin/helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Install MinIO
  command: /snap/bin/helm install minio bitnami/minio --set accessKey.password=minio-access-key --set secretKey.password=minio-secret-key --set service.type=NodePort --set service.nodePort=31002 --set defaultBuckets=openwhisk
