---
# file: roles/common/tasks/main.yml
- name: Disable ipv6 and swap
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: no
  with_items: "{{ sysctl }}"

# - name: Use closer mirrors
#   blockinfile:
#     path: /etc/apt/sources.list
#     insertbefore: BOF
#     block: |
#       deb mirror://mirrors.ubuntu.com/mirrors.txt bionic main restricted universe multiverse
#       deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-updates main restricted universe multiverse
#       deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-backports main restricted universe multiverse
#       deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-security main restricted universe multiverse

- name: Update cache and upgrade packages
  apt:
    upgrade: dist
    update_cache: yes
