@startuml
scale 2400*1600
hide footbox

actor user as u
participant FaaST as f
participant DataAwareness as da
participant DataMigration as dm
participant localDB as l
participant remoteDB as r

u -> f: function request
activate f

f -> f: checkPayload()
activate f
loop over every item
    f -> da: exists()
    activate da
    da -> l: exists()
    activate l
    da <-- l: bool
    deactivate l

    f <-- da: bool
    deactivate da
end
f <-- f: missingItems
deactivate f

alt not missing items
    f -> l: callFunction()
    activate l
    f <-- l:
    deactivate l
    u <-- f: function response
else missing items
    f ->> r: callFunction()
    activate r
    f <<-- r:
    deactivate r
    u <<-- f: function response
    f -> f: copyItems()
    activate f
    
    loop over every item
        f -> dm: copy(item)
        activate dm
        dm -> r: copy(item)
        activate r
        l <-- r: item
        deactivate r

        da <-- dm: update()

        activate da
        da -> f: copied
        deactivate da

        deactivate dm
    end
end

@enduml
