---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daemon
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daemon
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openwhisk
roleRef:
  kind: ClusterRole
  name: daemon
  apiGroup: rbac.authorization.k8s.io
