---
# file: roles/docker/tasks/main.yml
- name: Uninstall old packages
  apt:
    state: absent
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Install requirements
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add a GPG key for the packages
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  retries: 12 # Wait up to 1 min
  delay: 5

- name: Add repository for docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu  {{ ansible_lsb.codename }} stable
    state: present

- name: Install packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  # https://github.com/ansible/ansible/issues/51663
  register: result
  until: result is not failed
  retries: 12 # Wait up to 1 min
  delay: 5

- name: Adding existing user '{{ user }}' to group sudo
  user:
    name: "{{ user }}"
    groups:
      - docker
    append: yes

- name: Copy docker daemon config to host
  copy:
    src: "{{ role_path }}/files/daemon.json"
    dest: /etc/docker/daemon.json

- name: Enable service docker
  systemd:
    name: docker
    enabled: yes
    state: restarted
