@startuml

hide footbox

actor user as u
participant cli as c
participant watcher as w
participant openwhisk as o

u -> c: runScript()
activate c


c -> c: getSmallestAvg()
activate c
loop over every action
    c -> w: getAction()
    activate w
    c <-- w: executionTime
    deactivate w
    c -> c: compareTimes
end
c <-- c: smallestAvg
deactivate c

c -> o: callFunction()
activate o
c <-- o:
deactivate o

u <-- c: functionOutput
deactivate c

@enduml