---
# file: roles/minio-funtion/tasks/main.yml
- name: Download sample image
  get_url:
    url: https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png
    dest: /mnt/share/sample.png

- name: Copy sample image to bucket
  shell: |
    docker run -it -v '/mnt/share':'/mnt/share' --entrypoint="" --network host minio/mc sh -c " \
    mc config host add minio http://localhost:31003 minio-access-key minio-secret-key; \
    mc cp /mnt/share/sample.png minio/openwhisk "

- name: Create directory for the python function
  file:
    path: $PWD/minio-function
    state: directory
    mode: "0755"

- name: Copy python function
  template:
    src: "{{ role_path }}/templates/__main__.py.j2"
    dest: $PWD/minio-function/__main__.py

- name: Pack the function
  shell: |
    wsk -i action list | grep "minio"
    if [ $? -eq 0 ]; then
      wsk -i action delete minio
    fi
    cd minio-function
    wsk -i action create minio -t 300000 --docker ansjin/minio:actionbg __main__.py
