---
# file: roles/kubernetes/tasks/main.yml
- name: Add a GPG key for the packages
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: True
  register: result
  until: result is not failed
  retries: 12 # Wait up to 1 min
  delay: 5

- name: Add repository for kubernetes
  apt_repository:
    repo: deb  http://apt.kubernetes.io/  kubernetes-xenial  main
    state: present
  become: True

- name: Install kubernetes packages
  apt:
    pkg:
      - kubeadm=1.18.3-00
      - kubelet=1.18.3-00
      - kubectl=1.18.3-00
  become: True

# - name: Prevent packages from being upgraded.
#   dpkg_selections:
#     name: "{{ item }}"
#     selection: hold
#   with_items:
#     - kubeadm
#     - kubelet
#     - kubectl
#   become: True

- name: Add IP address to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ inventory_hostname }}$"
    line: "{{ hostvars[inventory_hostname].ansible_host }} {{ inventory_hostname }}"
    state: present
  become: True

- name: Copy kubeadm-config to host
  template:
    src: "{{ role_path }}/templates/kubeadm-config.yml.j2"
    dest: $PWD/kubeadm-config.yml
    mode: "0644"

- name: Copy cloud config to host
  template:
    src: "{{ role_path }}/templates/cloud.conf.j2"
    dest: /etc/kubernetes/cloud-config
  become: True

- name: Check cluster
  command: kubectl cluster-info
  register: cluster_info
  ignore_errors: True

- name: Run kubeadmin init
  shell: kubeadm init --config=kubeadm-config.yml --upload-certs | tee kubeadm-init.out
  become: True
  when: cluster_info.rc == 1

- name: Copy kubeadm-join-config to host
  template:
    src: "{{ role_path }}/templates/kubeadm-join-config.yml.j2"
    dest: $PWD/kubeadm-join-config.yml
    mode: "0644"

- name: Replace with correct values
  shell: |
    sed -i "s/token: .*/token: $(tail -n 2 kubeadm-init.out | grep -oP '.*token \K\w+\.\w+')/" kubeadm-join-config.yml
    sed -i "s/sha256:.*/sha256:$(tail -n 1 kubeadm-init.out | grep -oP '.*sha256:\K\w+')\"]/" kubeadm-join-config.yml

- name: Fetch kubeadm-join-config.yml
  fetch:
    src: kubeadm-join-config.yml
    dest: from_remote

- name: Create config directory for non-root user
  file:
    path: $PWD/.kube
    state: directory
    mode: "0755"

- name: Copy config file to non-root user directory
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: $PWD/.kube/config
    owner: "{{ user }}"
    group: "{{ user }}"
  become: True

- name: Fetch config
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: from_remote
  become: True

- name: Check for taint
  shell: kubectl describe node {{ ansible_hostname }} | grep "node-role.kubernetes.io/master:NoSchedule"
  register: hasTaint
  ignore_errors: True

- name: Remove the taint from master
  command: kubectl taint node {{ ansible_hostname }} node-role.kubernetes.io/master:NoSchedule-
  when: hasTaint is succeeded

- name: Copy files to host
  copy:
    src: "{{ item }}"
    dest: $PWD/
  with_fileglob:
    - "{{ role_path }}/files/*"

- name: Apply cloud-controller-manager-roles.yaml
  command: kubectl apply -f cloud-controller-manager-roles.yaml

- name: Apply cloud-controller-manager-role-bindings.yaml
  command: kubectl apply -f cloud-controller-manager-role-bindings.yaml

- name: Apply cloud-controller-manager.yaml
  command: kubectl apply -f cloud-controller-manager.yaml

- name: Get Kubernetes version
  shell: kubectl version | base64 -w 0
  register: k8sversion

- name: Apply the network plugin configuration
  # command: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version={{ k8sversion.stdout }}"
  command: kubectl apply -f https://docs.projectcalico.org/v3.15/manifests/calico.yaml

- name: Create Dashboard
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

- name: Copy dashboard-admin-user.yaml to the cluster
  copy:
    src: "{{ role_path }}/files/dashboard-admin-user.yaml"
    dest: $PWD/dashboard-admin-user.yaml

- name: Create the admin user
  command: kubectl apply -f dashboard-admin-user.yaml

- name: Save token to file
  shell: kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}') | grep "token:" | awk '{print $2}' | tee admin-user-token.out

- name: Fetch token from remote
  fetch:
    src: admin-user-token.out
    dest: from_remote

- name: Install helm
  snap:
    name: helm
    classic: yes
  become: True

- name: Get Helm releases
  shell: /snap/bin/helm list -A
  register: helm_releases

- name: Clone cinder's git repository
  git:
    repo: https://github.com/kubernetes/cloud-provider-openstack.git
    dest: $PWD/cinder
    force: yes

- name: Install Cinder
  command: /snap/bin/helm install cinder-csi cinder/charts/cinder-csi-plugin -n kube-system #--set storageClass.delete.isDefault=true
  when: helm_releases.stdout.find('cinder-csi') == -1

- name: Add stable repository
  command: /snap/bin/helm repo add stable https://kubernetes-charts.storage.googleapis.com

- name: Add bitnami repository
  command: /snap/bin/helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Update repositories
  command: /snap/bin/helm repo update

- name: Install NFS StorageClass
  command: /snap/bin/helm install nfs-client-provisioner stable/nfs-client-provisioner --set nfs.server={{ hostvars[groups.master.0].internal_ip }} --set nfs.path=/mnt/share --set storageClass.defaultClass=true
  when: helm_releases.stdout.find('nfs-client-provisioner') == -1

- name: Install InfluxDB
  command: /snap/bin/helm install influxdb bitnami/influxdb --set database=db --set adminUser.pwd=admin --set influxdb.service.type=NodePort --set influxdb.service.nodePorts.http=31002
  when: helm_releases.stdout.find('influxdb') == -1

- name: Install Prometheus for monitoring
  command: /snap/bin/helm install prometheus-operator stable/prometheus-operator -n prometheus-operator --create-namespace -f grafana-prometheus-values.yaml
  when: helm_releases.stdout.find('prometheus-operator') == -1
