grafana:
  grafana.ini:
    server:
      root_url: http://localhost:8001/api/v1/namespaces/prometheus-operator/services/http:prometheus-operator-grafana:service/proxy/
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "myprovider"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/myprovider
  dashboards:
    myprovider:
      one-node-exporter:
        datasource: Prometheus
        gnetId: 11074
        revision: 1
      k6-load-testing-results:
        datasource: influxdb
        gnetId: 2587
        revision: 3
  additionalDataSources:
    - name: influxdb
      access: proxy
      database: db
      basicAuth: true
      basicAuthPassword: admin
      basicAuthUser: admin
      editable: true
      orgId: 1
      type: influxdb
      url: http://influxdb.default:8086
      version: 1
